name: Whisper Transcription

on:
  push:
    paths:
      - '**.mp3'
      - 'transcribe.py'
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install tmate -y
          tmate -F
