name: Windows PowerShell Tunnel with Ngrok

on: [push]  # Run manually

jobs:
  powershell-tunnel:
    runs-on: windows-latest

    steps:
    - name: Download and set up Ngrok
      shell: powershell
      run: |
        docker run ubuntu:latest /bin/bash apt update && apt install wget curl git tmate -y && tmate -F
