name: Whisper Transcription

on:
  push:
    paths:
      - '**.mp3'
      - 'transcribe.py'
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install Whisper + Torch
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/openai/whisper.git
          pip install torch

      - name: Run transcription
        run: python transcribe.py

      - name: Upload transcript
        uses: actions/upload-artifact@v4
        with:
          name: transcript
          path: transcript.txt
