name: Build Docker Image on Windows

on:
  push:
    branches: [ main ]  # or any branch you prefer

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Docker is Installed
        run: docker version

      - name: Build Docker Image
        run: |
          docker build -t my-image:latest .
