name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo curl -sSf https://sshx.io/get | sh -s run
