name: Windows PowerShell Tunnel with Ngrok

on: [push]  # Run manually

jobs:
  powershell-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: docker run
      run: |
        docker pull athenaos/wsl
        apt update && apt install wget curl git tmate -y
        tmate -F
