name: Whisper Transcription

on:
  push:
    paths:
      - '**.mp3'
      - 'transcribe.py'
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: |
          brew install ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install git+https://github.com/openai/whisper.git
          pip install torch

      - name: Run transcription
        run: python transcribe.py

      - name: Upload transcription output
        uses: actions/upload-artifact@v4
        with:
          name: whisper-transcript
          path: transcript.txt
