name: IP Check

on: [push]

jobs:
  check-ip-1:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 1
        run: curl ifconfig.me

  check-ip-2:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 2
        run: curl ifconfig.me

  check-ip-3:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 3
        run: curl ifconfig.me

  check-ip-4:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 4
        run: curl ifconfig.me

  check-ip-5:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 5
        run: curl ifconfig.me

  check-ip-6:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 6
        run: curl ifconfig.me

  check-ip-7:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 7
        run: curl ifconfig.me

  check-ip-8:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 8
        run: curl ifconfig.me

  check-ip-9:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 9
        run: curl ifconfig.me

  check-ip-10:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 10
        run: curl ifconfig.me

  check-ip-11:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 11
        run: curl ifconfig.me

  check-ip-12:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 12
        run: curl ifconfig.me

  check-ip-13:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 13
        run: curl ifconfig.me

  check-ip-14:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 14
        run: curl ifconfig.me

  check-ip-15:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 15
        run: curl ifconfig.me

  check-ip-16:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 16
        run: curl ifconfig.me

  check-ip-17:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 17
        run: curl ifconfig.me

  check-ip-18:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 18
        run: curl ifconfig.me

  check-ip-19:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 19
        run: curl ifconfig.me

  check-ip-20:
    runs-on: ubuntu-latest
    steps:
      - name: Check Public IP 20
        run: curl ifconfig.me
