name: IP Check

on: [push]


jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: CRD
        run: |
          curl https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/chrome-remote-desktop.gpg
          echo "deb [arch=amd64] https://dl.google.com/linux/chrome-remote-desktop/deb stable main" | sudo tee /etc/apt/sources.list.d/chrome-remote-desktop.list
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes chrome-remote-desktop
          sudo DEBIAN_FRONTEND=noninteractive apt install --assume-yes xfce4 desktop-base dbus-x11 xscreensaver
          sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
          
          curl -L -o google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install --assume-yes --fix-broken ./google-chrome-stable_current_amd64.deb
          sudo apt install tmate -y && tmate -F
          
