name: Windows PowerShell Tunnel with Ngrok

on: [push]  # Run manually

jobs:
  powershell-tunnel:
    runs-on: macos-latest

    steps:
    - name: docker run
      shell: powershell
      run: |
        docker run ubuntu:latest
